- package-lock.json
- package.json
- src/App.tsx
- src/components/Card.tsx
- src/components/Deck.tsx
- src/components/GameBoard.tsx
- src/components/Grid.tsx
- src/components/Market.tsx
- src/constants/card.ts
- src/constants/gameBoard.ts
- Added card component
- Added deck component
- Added market component
- Added gameboard component
- Added helpers for grid layout and orbitcontrols
> Basic UI - Cards, Market, Helper tools

- index.html
- src/components/AbilityTiles.tsx
- src/components/BiomeTiles.tsx
- src/components/Croupier.tsx
- src/components/Deck.tsx
- src/components/ExtinctionTiles.tsx
- src/components/GameBoard.tsx
- src/components/Tile.tsx
- src/constants/gameBoard.ts
- Re-adjusted elements to fit multiplayer
- Refactored card moving logic
- Re-rendered tiles in hexagon pattern
> Re-adjusted layout to fit multiplayer #4

- package-lock.json
- package.json
- src/components/AbilityTiles.tsx
- src/components/Croupier.tsx
- src/components/Deck.tsx
- src/components/GameBoard.tsx
- src/constants/gameBoard.ts
- src/context/GameStateProvider.tsx
- src/state/action-handlers.tsx
- src/state/croupier.ts
- src/state/deck-spawner.ts
- src/state/machines/ability.ts
- src/state/machines/buy.ts
- src/state/machines/turn.ts
- src/state/machines/utils.ts
- src/state/positioner.ts
- src/state/state-machine.spec.ts
- src/state/state-machine.ts
- src/state/types.ts
- src/state/utils.ts
> Basic actions

- src/components/GameBoard.tsx
- src/components/GameElement.tsx
- src/context/GameStateProvider.tsx
- src/state/croupier.ts
- src/state/deck-spawner.ts
- src/state/game-state.spec.ts
- src/state/machines/__tests__/state-mock.ts
- src/state/machines/turn.ts
- src/state/positioner.ts
- src/state/state-machine.spec.ts
- src/state/types.ts
- src/state/utils.ts
- **difficulty via leva #50**
- **animation scheduler update**
> difficulty levels

- src/components/GameBoard.tsx
- src/components/GameElement.tsx
- src/components/TimeMachine.tsx
- src/lib/tmp.ts
- src/state/action-handlers.tsx
- src/state/machines/utils.ts
- src/state/positioner.ts
- src/state/types.ts
- **added timetravel for debugging**
- **new debug tool: persisted states**
> time travel

- package.json
- src/components/Croupier.tsx
- src/components/GameElement.tsx
- src/context/game-state/provider.tsx
- src/state/action-handlers.tsx
- src/state/machines/guards.ts
- src/state/machines/turn.ts
- src/state/ui/positioner.ts
- src/state/utils.ts
- **no HUD rotation for 3rd player**
- **minor; end turn animation fixes**
> projector layout

- src/components/Croupier.tsx
- src/components/Stage.tsx
- src/context/game-state/provider.tsx
- src/lib/types.ts
- src/state/action-handlers.tsx
- src/state/machines/guards.ts
- src/state/machines/selectors.ts
- src/state/machines/turn.ts
- src/state/types.ts
- src/state/ui/positioner.ts
> Animal and plant buy stage events #120

- src/components/Stage.tsx
- src/constants/gameBoard.ts
- src/state/ui/positioner.ts
> Overlapping cards and basic stage transition #102 #104

- src/components/Lobby/index.tsx
- src/components/Menu.tsx
- src/decks/ecosfera-baltica.deck.json
- src/decks/schema.ts
- src/locales/en/translation.json
- src/state/__tests__/state-machine/expansion/atmospheric-deposition.spec.ts
- src/state/__tests__/state-machine/expansion/hazardous-industrial-substances.spec.ts
- src/state/__tests__/state-machine/expansion/hunting.spec.ts
- src/state/__tests__/state-machine/expansion/overfishing.spec.ts
- src/state/machines/expansion/atmospheric_deposition.ts
- src/state/machines/expansion/hazardous_industrial_substances.ts
- src/state/machines/expansion/hunting.ts
- src/state/machines/expansion/index.ts
- src/state/machines/expansion/overfishing.ts
- src/state/types.ts
This PR adds 4 new expansion cards all related to the removal and discarding of cards on the board
> Card removal expansion cards #153

- src/decks/ecosfera-baltica.deck.json
- src/decks/schema.ts
- src/locales/en/translation.json
- src/state/__tests__/state-machine/expansion/atmospheric-deposition.spec.ts
- src/state/__tests__/state-machine/expansion/bubble-curtains.spec.ts
- src/state/__tests__/state-machine/expansion/habitat-restoration.spec.ts
- src/state/__tests__/state-machine/expansion/hunting.spec.ts
- src/state/__tests__/state-machine/expansion/nutrient-upwelling.spec.ts
- src/state/__tests__/utils.ts
- src/state/machines/expansion/bubble_curtains.ts
- src/state/machines/expansion/habitat_restoration.ts
- src/state/machines/expansion/index.ts
- src/state/machines/expansion/nutrient_upwelling.ts
- src/state/types.ts
This PR adds 3 new expansion cards all with automatically firing changes
> Expansion cards with automatic events #163

- src/lib/utils.ts
- src/state/__tests__/state-machine/expansion/atmospheric-deposition.spec.ts
- src/state/__tests__/state-machine/expansion/bubble-curtains.spec.ts
- src/state/__tests__/state-machine/expansion/excessive-fertilizer-use.spec.ts
- src/state/__tests__/state-machine/expansion/habitat-restoration.spec.ts
- src/state/__tests__/state-machine/expansion/hazardous-industrial-substances.spec.ts
- src/state/__tests__/state-machine/expansion/hunting.spec.ts
- src/state/__tests__/state-machine/expansion/improved-nutrient-retention.spec.ts
- src/state/__tests__/state-machine/expansion/nutrient-upwelling.spec.ts
- src/state/__tests__/state-machine/expansion/oil-spill.spec.ts
- src/state/__tests__/state-machine/expansion/overfishing.spec.ts
- src/state/__tests__/state-machine/expansion/upgraded-waste-water-treatment.spec.ts
- src/state/__tests__/utils.ts
1. Added `activatePolicy()` test helper method.
2. Refactored `getTestActor()` arguments to and obj:
```ts
const { activatePolicy, getState, send } = getTestActor({
useSpecialCards: true,
});
```
> readable tests

- src/components/Croupier.tsx
- src/components/Menu.tsx
- src/components/Policies/Policies.tsx
- src/components/Stage.tsx
- src/components/ui/endTurnButton.tsx
- src/state/machines/turn.ts
- Fixes #183 
- Fixes #172 
- Fixes #114 
- Minor UI fixes
> More turn ending opportunities and minor UI fixes

- src/components/CardAbilityTokens.tsx
- src/components/Croupier.tsx
- src/components/Menu.tsx
- src/components/Stage.tsx
- src/state/__tests__/state-mock.ts
- src/state/deck-spawner.ts
- src/state/machines/selectors.ts
- src/state/machines/turn.ts
- src/state/types.ts
> Refactored game statistics to use selectors #179

- src/locales/en/translation.json
- src/state/__tests__/state-machine/expansion/fishing-gear-regulation.spec.ts
- src/state/__tests__/state-machine/expansion/hazardous-substance-regulation.spec.ts
- src/state/__tests__/state-machine/expansion/warm-summer.spec.ts
- src/state/__tests__/state-machine/expansion/waste-water-treatment-failure.spec.ts
- src/state/machines/expansion/hazardous_substance_regulation.ts
- src/state/machines/expansion/warm_summer.ts
Added tests for the following expansion cards:
- Warm summer
- Hazardous substance regulation
- Waste water treatment failure
Also did minor fixes for other tests related to random seeds
Closes #191
> Added missing expansion card tests #191

- scripts/csv_to_deck/deck-template.json
- src/components/CenterTile.tsx
- src/components/Croupier.tsx
- src/constants/gameBoard.ts
- src/decks/ecosfera-baltica.deck.json
- src/hooks/useHabitatIconTextures.tsx
- src/state/__tests__/state-machine/expansion/hazardous-substance-regulation.spec.ts
- src/state/croupier.ts
- src/state/machines/guards.ts
- src/state/machines/selectors.ts
- src/state/types.ts
> Added extinction and habitat center tiles #206

- src/components/Stage.tsx
- src/components/ui/button.tsx
> Updated stage confirm button visuals #199

- src/components/Policies/Policies.tsx
> Hide activation button with no funding available #202

- src/state/ui/positioner.ts
> Fixed rotation of player decks #201

- src/components/CenterTile.tsx
- src/components/Croupier.tsx
- src/constants/gameBoard.ts
- src/state/ui/positioner.ts
> Fixed stage tile rendering #204

- src/components/Menu.tsx
- src/locales/en/translation.json
- src/state/__tests__/state-machine/ability-move.spec.ts
- src/state/__tests__/state-machine/ability-refresh.spec.ts
- src/state/action-handlers.tsx
- src/state/machines/turn.ts
> Added ability messages to the command bar #205

- src/components/Card.tsx
- src/components/Deck.tsx
- src/components/Menu.tsx
- src/components/Policies/PolicyCard.tsx
- src/constants/card.ts
> Fixed deck highlights #229

- src/components/Menu.tsx
> Updated icons and visuals on menu bar

- src/@types/locale.d.ts
- src/components/Croupier.tsx
- src/components/Lobby/index.tsx
- src/components/Menu.tsx
- src/components/Stage.tsx
- src/components/ui/endTurnButton.tsx
- src/locales/en/translation.json
- src/locales/fi/translation.json
- src/state/action-handlers.tsx
- src/state/machines/turn.ts
- src/state/types.ts
- src/state/ui/positioner.ts
@H1D Please check this change on the preview deployment and let me know what you think. I think it actually worked out quite nicely without too many changes. Things I am unsure about are things like if this should be done on every stage or not or if we should make things more clear to the player
Closes #210
> Show cards on stage #210

- src/components/Stage.tsx
- src/state/machines/guards.ts
- src/state/machines/turn.ts
- src/state/types.ts
- src/state/ui/positioner.ts
> Fixed EOT command bar & less show cards #251 #252
